### ISSUE TITLE
Fermi Paradox: Alien suns

### ISSUE THREAD

**Issue by joshbperry** [spacedecentral/hollyworlds#12]
Link Here: https://drive.google.com/open?id=1Rj7qDBUzdtAk1a-2OmdoN9rmcDpgV4Fpo551Fss5V_E

**Comment by joshbperry** [comment]
1st draft compete. Ready for editing

**Comment by MikkelHPANDA** [comment]
I have completed the editing review. Again, I used suggestion mode, which will be my default practice from here on. Well, except when I fail to notice that the software has defaulted back to editing mode ;-)

**Comment by joshbperry** [comment]
Approved all grammar and formatting edits, and did some minor re-writes to make a few things more clear.

**Comment by joshbperry** [comment]
Re-wrote a few paragraphs after another review of the literature on M-dwarfs

**Comment by MikkelHPANDA** [comment]
Okay. Starting a new edit review.

**Comment by MikkelHPANDA** [comment]
I have finished my second review.
