### ISSUE TITLE
Fermi Paradox: Rare Earth

### ISSUE THREAD

**Issue by joshbperry** [spacedecentral/hollyworlds#13]
Link here: https://drive.google.com/open?id=1DdcXI5GHjB859UHbFdUvAP2Ida8Edk41Lge2JWqKAgc

**Comment by joshbperry** [comment]
1st draft complete, ready for editing

**Comment by MikkelHPANDA** [comment]
Preliminary editing is complete.

**Comment by joshbperry** [comment]
Approved all edits and did a final read-through
