### ISSUE TITLE
Transcribe JR Skok interview

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/hollyworlds#20]
Transcribe the recorded audio into a written document, which will later be edited into an interview article.
There are two parts to the audio: JR-1 and JR-2. The different files with the same names are simply other versions of the same recording, likely obtained from my end or his end, or in another format. Some might have better audio than others, we need to see.

https://drive.google.com/drive/folders/1SigUy5496KpzAICRcUJVR8vQJue-Fr3O?usp=sharing

**Comment by joshbperry** [comment]
Finished the transcript

**Comment by Suzibianco** [comment]
Thank you @joshbperry How'd you do it so fast, did you use a transcribing software? Did my accent prove difficult to follow? I am sorry you had to go through this boring task, thank you so much!
