### ISSUE TITLE
Transcribe Henk Rogers interview

### ISSUE THREAD

**Issue by Suzibianco** [spacedecentral/hollyworlds#21]
Transcribe the recorded audio into a written document, which will later be edited into an interview article.
The different files with the same names are simply other versions of the same recording, likely obtained from my end or his end, or in another format. Some might have better audio than others, we need to see.

[https://drive.google.com/drive/folders/1lRWHQmL7AvWr1-XFfxF6XXeQICMDomeC?usp=sharing]

**Comment by MikkelHPANDA** [comment]
FYI, I am unable to open this document. The link appears to be deactivated, and the address does not work.
