### ISSUE TITLE
Summary of Mars Society 2019 conferance 

### ISSUE THREAD

**Issue by joshbperry** [spacedecentral/hollyworlds#26]
https://drive.google.com/open?id=1rZ9_yV1drJ205x3wItAnGicu4jtJipxoU00XkB9aneM

**Comment by MikkelHPANDA** [comment]
Finished preliminary edit review.

**Comment by joshbperry** [comment]
Implemented pretty much all suggestions, since they were related to grammar and formatting.

**Comment by MikkelHPANDA** [comment]
Okay, looks good. Should be all ready to go. I did a little tweek on the format ("justified" paragraphs) to clean up the layout visually. I also replaced "may" (permission) with "might" (possibility).
