### ISSUE TITLE
Fermi Paradox: Galactic Dead Zones

### ISSUE THREAD

**Issue by joshbperry** [spacedecentral/hollyworlds#9]
Link Here: https://docs.google.com/document/d/1AJFAEyk84mq9edbo-r5QTC4IgdfRY3MmdoY-wJr_ak8/edit?usp=sharing

**Comment by joshbperry** [comment]
Finished recommended re-writes

**Comment by MikkelHPANDA** [comment]
Completed edits. I decided to use suggestion editing, in case if someone disagrees with the changes. This will require a more active final review, however. I have included some comments regarding the arguments, as well. These do not necessarily require any change in text, but they might be useful for further articles.

**Comment by joshbperry** [comment]
I incorporated most of your recommendations and did a final read-through, but I do think that some of the points you made are better addressed later in the series.
